export enum MarketingTactic {
  AbandonedCart = "ABANDONED_CART",
  Ad = "AD",
  Affiliate = "AFFILIATE",
  Link = "LINK",
  Loyalty = "LOYALTY",
  Message = "MESSAGE",
  Newsletter = "NEWSLETTER",
  Notification = "NOTIFICATION",
  Post = "POST",
  Retargeting = "RETARGETING",
  Transactional = "TRANSACTIONAL",
  Seo = "SEO",
  Direct = "DIRECT",
  StorefrontApp = "STOREFRONT_APP",
  Display = "DISPLAY",
  Search = "SEARCH",
  FollowUp = "FOLLOW_UP",
  Receipt = "RECEIPT",
}