export enum StaffMemberPermission {
  Applications = "APPLICATIONS",
  Channels = "CHANNELS",
  Customers = "CUSTOMERS",
  Dashboard = "DASHBOARD",
  Domains = "DOMAINS",
  DraftOrders = "DRAFT_ORDERS",
  Full = "FULL",
  GiftCards = "GIFT_CARDS",
  Links = "LINKS",
  Locations = "LOCATIONS",
  Marketing = "MARKETING",
  MarketingSection = "MARKETING_SECTION",
  Orders = "ORDERS",
  Overviews = "OVERVIEWS",
  Pages = "PAGES",
  Preferences = "PREFERENCES",
  Products = "PRODUCTS",
  Reports = "REPORTS",
  Themes = "THEMES",
}